# Generated by Django 2.1.3 on 2018-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('urgency_level', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('relief_center_id', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
