# Generated by Django 2.1.3 on 2018-11-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField()),
                ('location', models.TextField()),
                ('donation_received', models.IntegerField()),
                ('type_of_disaster', models.CharField(max_length=100)),
            ],
        ),
    ]
