# Generated by Django 2.1.3 on 2018-11-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcenter',
            name='contact_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reliefcenter',
            name='donation_received',
            field=models.PositiveIntegerField(),
        ),
    ]
