# Generated by Django 2.1.3 on 2018-11-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relief_center', '0002_auto_20181110_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliefcenter',
            old_name='contact_no',
            new_name='contact',
        ),
    ]
