# Generated by Django 2.1.3 on 2018-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief_center', '0003_auto_20181110_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcenter',
            name='type_of_disaster',
            field=models.TextField(),
        ),
    ]
