# Generated by Django 2.1.3 on 2018-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief_center', '0004_auto_20181110_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcenter',
            name='type_of_disaster',
            field=models.TextField(max_length=100),
        ),
    ]
