# Generated by Django 2.1.3 on 2018-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief_center', '0006_auto_20181110_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcenter',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reliefcenter',
            name='type_of_disaster',
            field=models.CharField(max_length=100),
        ),
    ]
